[Feat] -  Check for command
CMEPW/Yelaa pull request #18
Opened 2021-10-29 18:38 UTC by jenaye

2021-10-29 18:52 UTC, jenaye commented
maybe should use function like this 


```go
func commandExists(cmd string) bool {
	_, err := exec.LookPath(cmd)
	color.Red("Please define command : %v  in ure path => %q", cmd, err)
	color.Red("you can use alias like this : dirsearch='python /home/<user>/softs/dirsearch/dirsearch.py'")
	return false
}
```

2021-10-29 20:32 UTC, darkweak approved these changes

2021-10-30 23:34 UTC, darkweak requested changes

2021-10-30 23:34 UTC, darkweak commented on main.go
> +	if err != nil {
```suggestion
	if commandExists("dirsearch") {
```

2021-10-30 23:34 UTC, darkweak commented on main.go
> +	if err != nil {
Same

2021-10-30 23:36 UTC, darkweak requested changes

2021-10-30 23:36 UTC, darkweak commented on main.go
> +		os.Exit(0)
It should exit with the status 1

2021-10-31 11:48 UTC, merged